2017-08-27 14:15:28,771 [Dummy-1:140685584279296] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-27 14:15:28,774 [Dummy-1:140685584279296] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-27 14:16:49,927 [Dummy-1:139708937410304] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-27 14:16:49,933 [Dummy-1:139708937410304] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-27 14:16:55,151 [Thread-2:139708695152384] [crawlermanage.views:544] [INFO]- vdfgdf#iouyi#iuo
2017-08-27 14:17:39,004 [Dummy-1:140592043480832] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-27 14:17:39,007 [Dummy-1:140592043480832] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-27 14:23:19,218 [Thread-2:140591795009280] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-27 14:23:39,280 [Thread-8:140591753045760] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-27 14:25:44,590 [Dummy-1:140611592124160] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-27 14:25:44,601 [Dummy-1:140611592124160] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-27 14:26:05,717 [Dummy-1:140635538626304] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-27 14:26:05,720 [Dummy-1:140635538626304] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-27 14:26:07,997 [Thread-2:140635499521792] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-27 14:26:36,837 [Dummy-1:139879747544832] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-27 14:26:36,839 [Dummy-1:139879747544832] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-27 14:26:38,482 [Thread-2:139879501526784] [crawlermanage.views:545] [INFO]- ggdf#dfg
2017-08-27 14:26:38,482 [Thread-2:139879501526784] [crawlermanage.views:550] [INFO]- ggdf#dfg
2017-08-27 14:26:38,486 [Thread-2:139879501526784] [crawlermanage.views:551] [INFO]- ggdf#dfg
2017-08-27 14:27:06,823 [Dummy-1:139946027779840] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-27 14:27:06,829 [Dummy-1:139946027779840] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-27 14:27:12,876 [Thread-2:139945785546496] [crawlermanage.views:545] [INFO]- true
2017-08-27 14:27:12,877 [Thread-2:139945785546496] [crawlermanage.views:546] [INFO]- ggdf#dfg
2017-08-27 14:27:12,877 [Thread-2:139945785546496] [crawlermanage.views:551] [INFO]- 1
2017-08-27 14:27:43,031 [Dummy-1:140006224520960] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-27 14:27:43,033 [Dummy-1:140006224520960] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-27 14:27:46,428 [Thread-2:140005982459648] [crawlermanage.views:545] [INFO]- <type 'unicode'>
2017-08-27 14:27:46,429 [Thread-2:140005982459648] [crawlermanage.views:546] [INFO]- ggdf#dfg
2017-08-27 14:27:46,429 [Thread-2:140005982459648] [crawlermanage.views:551] [INFO]- 1
2017-08-27 14:34:40,105 [Dummy-1:140531396769536] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-27 14:34:40,108 [Dummy-1:140531396769536] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-27 14:34:41,181 [Thread-2:140531356092160] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-27 14:35:22,165 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-27 14:35:22,169 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-27 14:35:22,170 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-27 14:35:22,173 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-27 14:35:22,252 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'logentry' AND "django_content_type"."app_label" = 'admin'); args=('logentry', 'admin')
2017-08-27 14:35:22,260 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (1) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(1,)
2017-08-27 14:35:22,262 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'admin'; args=('admin',)
2017-08-27 14:35:22,263 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'permission' AND "django_content_type"."app_label" = 'auth'); args=('permission', 'auth')
2017-08-27 14:35:22,267 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'group' AND "django_content_type"."app_label" = 'auth'); args=('group', 'auth')
2017-08-27 14:35:22,269 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'user' AND "django_content_type"."app_label" = 'auth'); args=('user', 'auth')
2017-08-27 14:35:22,274 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (2, 3, 4) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(2, 3, 4)
2017-08-27 14:35:22,276 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'auth'; args=('auth',)
2017-08-27 14:35:22,277 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'contenttype' AND "django_content_type"."app_label" = 'contenttypes'); args=('contenttype', 'contenttypes')
2017-08-27 14:35:22,280 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (5) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(5,)
2017-08-27 14:35:22,281 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'contenttypes'; args=('contenttypes',)
2017-08-27 14:35:22,282 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'session' AND "django_content_type"."app_label" = 'sessions'); args=('session', 'sessions')
2017-08-27 14:35:22,290 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (6) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(6,)
2017-08-27 14:35:22,291 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'sessions'; args=('sessions',)
2017-08-27 14:35:30,177 [Dummy-1:140456988780288] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-27 14:35:30,180 [Dummy-1:140456988780288] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-27 14:35:37,471 [Thread-2:140456746583808] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-27 14:36:22,534 [Thread-8:140456495146752] [crawlermanage.views:545] [INFO]- <type 'unicode'>
2017-08-27 14:36:22,534 [Thread-8:140456495146752] [crawlermanage.views:546] [INFO]- http://119.125.53.23:8080#http://192.168.1.110:80
2017-08-28 10:57:38,224 [MainThread:140522502706944] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-28 10:57:38,248 [MainThread:140522502706944] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-28 10:57:38,249 [MainThread:140522502706944] [django.db.backends:89] [DEBUG]- (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-28 10:57:38,250 [MainThread:140522502706944] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-28 10:57:38,338 [MainThread:140522502706944] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'logentry' AND "django_content_type"."app_label" = 'admin'); args=('logentry', 'admin')
2017-08-28 10:57:38,348 [MainThread:140522502706944] [django.db.backends:89] [DEBUG]- (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (1) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(1,)
2017-08-28 10:57:38,353 [MainThread:140522502706944] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'admin'; args=('admin',)
2017-08-28 10:57:38,355 [MainThread:140522502706944] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'permission' AND "django_content_type"."app_label" = 'auth'); args=('permission', 'auth')
2017-08-28 10:57:38,356 [MainThread:140522502706944] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'group' AND "django_content_type"."app_label" = 'auth'); args=('group', 'auth')
2017-08-28 10:57:38,358 [MainThread:140522502706944] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'user' AND "django_content_type"."app_label" = 'auth'); args=('user', 'auth')
2017-08-28 10:57:38,360 [MainThread:140522502706944] [django.db.backends:89] [DEBUG]- (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (2, 3, 4) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(2, 3, 4)
2017-08-28 10:57:38,361 [MainThread:140522502706944] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'auth'; args=('auth',)
2017-08-28 10:57:38,371 [MainThread:140522502706944] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'contenttype' AND "django_content_type"."app_label" = 'contenttypes'); args=('contenttype', 'contenttypes')
2017-08-28 10:57:38,373 [MainThread:140522502706944] [django.db.backends:89] [DEBUG]- (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (5) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(5,)
2017-08-28 10:57:38,375 [MainThread:140522502706944] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'contenttypes'; args=('contenttypes',)
2017-08-28 10:57:38,376 [MainThread:140522502706944] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'session' AND "django_content_type"."app_label" = 'sessions'); args=('session', 'sessions')
2017-08-28 10:57:38,378 [MainThread:140522502706944] [django.db.backends:89] [DEBUG]- (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (6) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(6,)
2017-08-28 10:57:38,379 [MainThread:140522502706944] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'sessions'; args=('sessions',)
2017-08-28 11:42:35,084 [Dummy-1:139744397825792] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-28 11:42:35,087 [Dummy-1:139744397825792] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-28 11:42:56,377 [Thread-2:139744357410560] [django.template:927] [DEBUG]- Exception while resolving variable 'error' in template 'crawlermanage/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error] in u"[{'False': False, 'None': None, 'True': True}]"
2017-08-28 11:42:57,221 [Thread-3:139744142948096] [django.template:927] [DEBUG]- Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
2017-08-28 11:43:24,790 [Dummy-1:140347854288640] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-28 11:43:24,794 [Dummy-1:140347854288640] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-28 11:43:31,715 [Thread-3:140347806004992] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 11:44:29,927 [Thread-9:140347797612288] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 11:44:48,053 [Dummy-1:140612304926464] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-28 11:44:48,057 [Dummy-1:140612304926464] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-28 11:44:55,023 [Thread-3:140612061886208] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 11:46:39,123 [Dummy-1:139704292472576] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-28 11:46:39,129 [Dummy-1:139704292472576] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-28 11:46:40,555 [Thread-2:139704050378496] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 11:46:40,991 [Thread-3:139704050378496] [crawlermanage.views:555] [INFO]- Proxy object
2017-08-28 11:47:14,514 [Dummy-1:139759537592064] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-28 11:47:14,516 [Dummy-1:139759537592064] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-28 11:47:18,261 [Thread-2:139759295497984] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 11:47:20,440 [Thread-3:139759295497984] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 11:47:21,007 [Thread-4:139759286580992] [crawlermanage.views:555] [INFO]- Proxy object
2017-08-28 11:47:21,007 [Thread-4:139759286580992] [crawlermanage.views:556] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 11:47:21,007 [Thread-4:139759286580992] [crawlermanage.views:557] [INFO]- 1
2017-08-28 11:49:24,361 [Thread-8:139759269795584] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 11:49:24,798 [Thread-9:139759278188288] [crawlermanage.views:555] [INFO]- Proxy object
2017-08-28 11:49:24,798 [Thread-9:139759278188288] [crawlermanage.views:556] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 11:49:24,798 [Thread-9:139759278188288] [crawlermanage.views:557] [INFO]- 1
2017-08-28 11:49:59,869 [Dummy-1:140466047608576] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-28 11:49:59,871 [Dummy-1:140466047608576] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-28 11:50:21,512 [Thread-2:140465805551360] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 11:50:22,007 [Thread-3:140465797158656] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 11:50:22,008 [Thread-3:140465797158656] [crawlermanage.views:556] [INFO]- 1
2017-08-28 11:50:33,528 [Thread-8:140465554843392] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 11:50:34,171 [Thread-9:140465563236096] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 11:50:34,172 [Thread-9:140465563236096] [crawlermanage.views:556] [INFO]- 1
2017-08-28 11:51:19,022 [Thread-14:140465805551360] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 11:51:19,398 [Thread-15:140465797158656] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 11:51:19,398 [Thread-15:140465797158656] [crawlermanage.views:556] [INFO]- 1
2017-08-28 11:51:23,446 [Thread-16:140465788765952] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 11:51:24,068 [Thread-17:140465780373248] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 11:51:24,068 [Thread-17:140465780373248] [crawlermanage.views:556] [INFO]- 1
2017-08-28 11:53:38,150 [Thread-22:140465554843392] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 11:53:38,619 [Thread-23:140465563236096] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 11:53:38,620 [Thread-23:140465563236096] [crawlermanage.views:556] [INFO]- 1
2017-08-28 11:54:06,846 [Thread-28:140465797158656] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 11:54:07,279 [Thread-29:140465788765952] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 11:54:07,279 [Thread-29:140465788765952] [crawlermanage.views:556] [INFO]- 1
2017-08-28 11:54:16,590 [Thread-30:140465805551360] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 11:54:17,059 [Thread-34:140465788765952] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 11:54:17,059 [Thread-34:140465788765952] [crawlermanage.views:556] [INFO]- 1
2017-08-28 11:54:35,608 [Thread-36:140465797158656] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 11:54:36,202 [Thread-37:140465788765952] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 11:54:36,203 [Thread-37:140465788765952] [crawlermanage.views:556] [INFO]- 1
2017-08-28 11:54:38,345 [Thread-38:140465563236096] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 11:54:38,942 [Thread-39:140465554843392] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 11:54:38,942 [Thread-39:140465554843392] [crawlermanage.views:556] [INFO]- 1
2017-08-28 11:54:41,112 [Thread-40:140465805551360] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 11:54:41,507 [Thread-41:140465780373248] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 11:54:41,508 [Thread-41:140465780373248] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:02:07,033 [Thread-46:140465563236096] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:02:07,516 [Thread-47:140465797158656] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:02:07,517 [Thread-47:140465797158656] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:02:46,512 [Thread-52:140465780373248] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:02:47,004 [Thread-53:140465554843392] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:02:47,004 [Thread-53:140465554843392] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:06:57,594 [Thread-58:140465563236096] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:06:58,090 [Thread-59:140465797158656] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:06:58,091 [Thread-59:140465797158656] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:07:00,552 [Thread-60:140465788765952] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:07:00,911 [Thread-61:140465805551360] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:07:00,911 [Thread-61:140465805551360] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:07:07,132 [Thread-62:140465780373248] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:07:07,910 [Thread-64:140465797158656] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:07:07,910 [Thread-64:140465797158656] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:07:10,315 [Thread-65:140465563236096] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:07:10,934 [Thread-66:140465563236096] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:07:10,934 [Thread-66:140465563236096] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:07:13,488 [Thread-67:140465563236096] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:07:13,925 [Thread-68:140465563236096] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:07:13,925 [Thread-68:140465563236096] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:07:34,538 [Thread-69:140465563236096] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:07:35,055 [Thread-70:140465563236096] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:07:35,055 [Thread-70:140465563236096] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:07:37,684 [Thread-71:140465563236096] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:07:38,233 [Thread-72:140465563236096] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:07:38,235 [Thread-72:140465563236096] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:10:03,814 [Thread-73:140465563236096] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:10:04,367 [Thread-74:140465563236096] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:10:04,367 [Thread-74:140465563236096] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:10:32,385 [Thread-75:140465563236096] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:10:32,964 [Thread-76:140465563236096] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:10:32,964 [Thread-76:140465563236096] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:10:52,321 [Thread-77:140465563236096] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:11:38,308 [Thread-78:140465563236096] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:11:38,926 [Thread-79:140465563236096] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:11:38,927 [Thread-79:140465563236096] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:11:58,473 [Thread-80:140465563236096] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:11:59,113 [Thread-81:140465563236096] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:11:59,113 [Thread-81:140465563236096] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:14:31,088 [Thread-82:140465563236096] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:14:31,660 [Thread-83:140465563236096] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:14:31,660 [Thread-83:140465563236096] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:14:34,473 [Thread-84:140465563236096] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:14:35,120 [Thread-85:140465563236096] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:14:35,120 [Thread-85:140465563236096] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:14:54,269 [Thread-86:140465563236096] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:14:54,830 [Thread-87:140465563236096] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:14:54,831 [Thread-87:140465563236096] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:14:57,840 [Thread-88:140465563236096] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:14:58,349 [Thread-89:140465563236096] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:14:58,349 [Thread-89:140465563236096] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:15:37,998 [Thread-90:140465563236096] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:15:38,625 [Thread-91:140465563236096] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:15:38,625 [Thread-91:140465563236096] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:17:19,151 [Thread-92:140465563236096] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:17:19,838 [Thread-93:140465563236096] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:17:19,839 [Thread-93:140465563236096] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:17:35,665 [Thread-94:140465563236096] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:17:36,299 [Thread-95:140465563236096] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:17:36,299 [Thread-95:140465563236096] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:19:14,603 [Thread-96:140465563236096] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:19:15,166 [Thread-97:140465563236096] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:19:15,167 [Thread-97:140465563236096] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:25:50,273 [Dummy-1:139686630127360] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-28 12:25:50,276 [Dummy-1:139686630127360] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-28 12:25:53,853 [Thread-2:139686589449984] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:25:54,360 [Thread-3:139686589449984] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:25:54,361 [Thread-3:139686589449984] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:26:02,215 [Thread-5:139686589449984] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:26:02,774 [Thread-6:139686589449984] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:26:02,774 [Thread-6:139686589449984] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:26:57,017 [Dummy-1:140503064942336] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-28 12:26:57,023 [Dummy-1:140503064942336] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-28 12:26:57,633 [Thread-2:140503024264960] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:26:58,650 [Thread-3:140503024264960] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:26:58,651 [Thread-3:140503024264960] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:27:57,093 [Thread-5:140503024264960] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:28:00,055 [Dummy-1:139735034668800] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-28 12:28:00,058 [Dummy-1:139735034668800] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-28 12:28:07,033 [Thread-2:139734792521472] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:28:07,678 [Thread-3:139734792521472] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:28:07,679 [Thread-3:139734792521472] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:28:45,361 [Thread-4:139734792521472] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:28:45,860 [Thread-5:139734783604480] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:28:45,861 [Thread-5:139734783604480] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:28:58,024 [Thread-10:139734758426368] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:28:58,934 [Thread-11:139734412162816] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:28:58,934 [Thread-11:139734412162816] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:29:16,417 [Thread-16:139734792521472] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:29:17,052 [Thread-17:139734783604480] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:29:17,052 [Thread-17:139734783604480] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:29:17,249 [Thread-18:139734775211776] [crawlermanage.views:561] [INFO]- true
2017-08-28 12:29:19,061 [Thread-19:139734766819072] [crawlermanage.views:561] [INFO]- false
2017-08-28 12:29:19,156 [Thread-19:139734766819072] [crawlermanage.views:569] [INFO]- 1
2017-08-28 12:29:25,571 [Thread-20:139734758426368] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:29:25,974 [Thread-21:139734412162816] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:29:25,974 [Thread-21:139734412162816] [crawlermanage.views:556] [INFO]- 0
2017-08-28 12:29:28,042 [Thread-22:139734766819072] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:29:28,520 [Thread-23:139734775211776] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:29:28,520 [Thread-23:139734775211776] [crawlermanage.views:556] [INFO]- 0
2017-08-28 12:29:37,596 [Thread-26:139734412162816] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:29:38,369 [Thread-28:139734792521472] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:29:38,369 [Thread-28:139734792521472] [crawlermanage.views:556] [INFO]- 0
2017-08-28 12:29:41,137 [Thread-29:139734783604480] [crawlermanage.views:561] [INFO]- true
2017-08-28 12:29:42,385 [Thread-30:139734775211776] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:29:42,813 [Thread-31:139734783604480] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:29:42,813 [Thread-31:139734783604480] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:29:43,022 [Thread-32:139734792521472] [crawlermanage.views:561] [INFO]- true
2017-08-28 12:29:49,643 [Thread-33:139734758426368] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:29:50,189 [Thread-34:139734792521472] [crawlermanage.views:555] [INFO]- 192.168.2.2#213.21.1.2
2017-08-28 12:29:50,190 [Thread-34:139734792521472] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:29:50,353 [Thread-35:139734783604480] [crawlermanage.views:561] [INFO]- true
2017-08-28 12:30:30,566 [Thread-37:139734783604480] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:30:31,023 [Thread-38:139734792521472] [crawlermanage.views:555] [INFO]- http://123.213.23.23:8080#https://34.32.12.21:80
2017-08-28 12:30:31,023 [Thread-38:139734792521472] [crawlermanage.views:556] [INFO]- 1
2017-08-28 12:30:31,204 [Thread-39:139734792521472] [crawlermanage.views:561] [INFO]- true
2017-08-28 12:30:46,894 [Dummy-1:140628030826240] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-28 12:30:46,896 [Dummy-1:140628030826240] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-28 12:38:52,240 [Thread-2:140627991459584] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:38:52,882 [Thread-4:140627991459584] [crawlermanage.views:561] [INFO]- true
2017-08-28 12:46:41,985 [Thread-5:140627991459584] [django.template:927] [DEBUG]- Exception while resolving variable 'tasklist' in template 'crawlermanage/tasks.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [tasklist] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fe680ecb578>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fe680f18488>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fe680ec47d0>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fe680ee31d0>, u\'request\': <WSGIRequest: GET \'/crawlermanage/tasks/\'>}, {}, {\'p2\': <crawlermanage.utils.page.paging instance at 0x7fe680f01050>, \'status\': \'currenttask\', \'pausing_count\': 4, \'error_count\': 0, \'p\': <crawlermanage.utils.page.paging instance at 0x7fe680f01638>, \'running_count\': 3, \'stopping_count\': 4}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n\\n\\n<!--<div class="box">-\'>, <Variable Node: running_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: pausing_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: stopping_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: error_count>, <TextNode: u\'</span>\\n            </div\'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n\\n            </ul>\\n     \'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n\\n\\n\\n                  <di\'>, <For Node: for task in tasklist, tail_len: 11>, <TextNode: u\'\\n\\t\\t\\t                \\n  \\t\\t\'>, <For Node: for i in p.p_content, tail_len: 33>, <TextNode: u\'\\n                        \'>, <Variable Node: p.p_count>, <TextNode: u\'</span> \\u6761\\u8bb0\\u5f55\\uff0c\\u603b <span  clas\'>, <Variable Node: p.p_pages>, <TextNode: u\'</span> \\u9875\\uff0c\\u5f53\\u524d\\u5728<span class=\'>, <Variable Node: p.page>, <TextNode: u\'</span>\\u9875\\n                \'>, <django.template.defaulttags.URLNode object at 0x7fe680ea8e50>, <TextNode: u\'?page=\'>, <Variable Node: p.p_previous>, <TextNode: u\'">&laquo;</a></li>\\n      \'>, <django.template.defaulttags.URLNode object at 0x7fe680eb0050>, <TextNode: u\'?page=1">\\u9996\\u9875</a></li>\\n    \'>, <For Node: for i in p.p_range, tail_len: 9>, <TextNode: u\'\\n                        \'>, <django.template.defaulttags.URLNode object at 0x7fe680eb0650>, <TextNode: u\'?page=\'>, <Variable Node: p.p_pages>, <TextNode: u\'">\\u5c3e\\u9875</a></li>\\n           \'>, <django.template.defaulttags.URLNode object at 0x7fe680eb0810>, <TextNode: u\'?page=\'>, <Variable Node: p.p_next>, <TextNode: u\'">&raquo;</a></li>\\n      \'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n              <!--<div c\'>, <For Node: for i in p2.p_content, tail_len: 27>, <TextNode: u\'\\n                        \'>, <Variable Node: p2.p_count>, <TextNode: u\'</span> \\u6761\\u8bb0\\u5f55\\uff0c\\u603b <span  clas\'>, <Variable Node: p2.p_pages>, <TextNode: u\'</span> \\u9875\\uff0c\\u5f53\\u524d\\u5728<span class=\'>, <Variable Node: p2.page>, <TextNode: u\'</span>\\u9875\\n                \'>, <django.template.defaulttags.URLNode object at 0x7fe680ebd6d0>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_previous>, <TextNode: u\'">&laquo;</a></li>\\n      \'>, <django.template.defaulttags.URLNode object at 0x7fe680ebd890>, <TextNode: u\'?page2=1">\\u9996\\u9875</a></li>\\n   \'>, <For Node: for i in p2.p_range, tail_len: 9>, <TextNode: u\'\\n                        \'>, <django.template.defaulttags.URLNode object at 0x7fe680ebde90>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_pages>, <TextNode: u\'">\\u5c3e\\u9875</a></li>\\n           \'>, <django.template.defaulttags.URLNode object at 0x7fe680ec4090>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_next>, <TextNode: u\'">&raquo;</a></li>\\n      \'>]>}, {}]'
2017-08-28 12:46:42,055 [Thread-5:140627991459584] [django.template:927] [DEBUG]- Exception while resolving variable 'page' in template 'crawlermanage/tasks.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [page] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fe680ecb578>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fe680f18488>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fe680ec47d0>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fe680ee31d0>, u\'request\': <WSGIRequest: GET \'/crawlermanage/tasks/\'>}, {}, {\'p2\': <crawlermanage.utils.page.paging instance at 0x7fe680f01050>, \'status\': \'currenttask\', \'pausing_count\': 4, \'error_count\': 0, \'p\': <crawlermanage.utils.page.paging instance at 0x7fe680f01638>, \'running_count\': 3, \'stopping_count\': 4}, {\'block\': <Block Node: script. Contents: [<TextNode: u\'\\n<script src="../../stati\'>, <Variable Node: page>, <TextNode: u\'"\\n                  if(pa\'>]>}]'
2017-08-28 12:46:43,696 [Thread-6:140627991459584] [django.template:927] [DEBUG]- Exception while resolving variable 'error1' in template 'crawlermanage/layout.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error1] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'ips\': [<Machine: Machine object>, <Machine: Machine object>, <Machine: Machine object>]}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n<div class="box box-prim\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fe680ef8dd0>, <TextNode: u\'-->\\n              <!-- te\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <Variable Node: error2>, <TextNode: u\'</p>\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <For Node: for i in ips, tail_len: 5>, <TextNode: u\'\\n                        \'>]>}]'
2017-08-28 12:46:43,701 [Thread-6:140627991459584] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/layout.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'ips\': [<Machine: Machine object>, <Machine: Machine object>, <Machine: Machine object>]}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n<div class="box box-prim\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fe680ef8dd0>, <TextNode: u\'-->\\n              <!-- te\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <Variable Node: error2>, <TextNode: u\'</p>\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <For Node: for i in ips, tail_len: 5>, <TextNode: u\'\\n                        \'>]>}]'
2017-08-28 12:46:43,702 [Thread-6:140627991459584] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/layout.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'ips\': [<Machine: Machine object>, <Machine: Machine object>, <Machine: Machine object>]}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n<div class="box box-prim\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fe680ef8dd0>, <TextNode: u\'-->\\n              <!-- te\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <Variable Node: error2>, <TextNode: u\'</p>\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <For Node: for i in ips, tail_len: 5>, <TextNode: u\'\\n                        \'>]>}]'
2017-08-28 12:46:43,704 [Thread-6:140627991459584] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/layout.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'ips\': [<Machine: Machine object>, <Machine: Machine object>, <Machine: Machine object>]}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n<div class="box box-prim\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fe680ef8dd0>, <TextNode: u\'-->\\n              <!-- te\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <Variable Node: error2>, <TextNode: u\'</p>\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <For Node: for i in ips, tail_len: 5>, <TextNode: u\'\\n                        \'>]>}]'
2017-08-28 12:46:45,026 [Thread-7:140627991459584] [django.template:927] [DEBUG]- Exception while resolving variable 'tasklist' in template 'crawlermanage/tasks.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [tasklist] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fe680e74050>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fe680ef2a28>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fe680ef8dd0>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fe680ef8190>, u\'request\': <WSGIRequest: GET \'/crawlermanage/tasks/\'>}, {}, {\'p2\': <crawlermanage.utils.page.paging instance at 0x7fe680ed6b00>, \'status\': \'currenttask\', \'pausing_count\': 4, \'error_count\': 0, \'p\': <crawlermanage.utils.page.paging instance at 0x7fe680f97fc8>, \'running_count\': 3, \'stopping_count\': 4}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n\\n\\n<!--<div class="box">-\'>, <Variable Node: running_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: pausing_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: stopping_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: error_count>, <TextNode: u\'</span>\\n            </div\'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n\\n            </ul>\\n     \'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n\\n\\n\\n                  <di\'>, <For Node: for task in tasklist, tail_len: 11>, <TextNode: u\'\\n\\t\\t\\t                \\n  \\t\\t\'>, <For Node: for i in p.p_content, tail_len: 33>, <TextNode: u\'\\n                        \'>, <Variable Node: p.p_count>, <TextNode: u\'</span> \\u6761\\u8bb0\\u5f55\\uff0c\\u603b <span  clas\'>, <Variable Node: p.p_pages>, <TextNode: u\'</span> \\u9875\\uff0c\\u5f53\\u524d\\u5728<span class=\'>, <Variable Node: p.page>, <TextNode: u\'</span>\\u9875\\n                \'>, <django.template.defaulttags.URLNode object at 0x7fe680ebdf10>, <TextNode: u\'?page=\'>, <Variable Node: p.p_previous>, <TextNode: u\'">&laquo;</a></li>\\n      \'>, <django.template.defaulttags.URLNode object at 0x7fe680eba110>, <TextNode: u\'?page=1">\\u9996\\u9875</a></li>\\n    \'>, <For Node: for i in p.p_range, tail_len: 9>, <TextNode: u\'\\n                        \'>, <django.template.defaulttags.URLNode object at 0x7fe680eba710>, <TextNode: u\'?page=\'>, <Variable Node: p.p_pages>, <TextNode: u\'">\\u5c3e\\u9875</a></li>\\n           \'>, <django.template.defaulttags.URLNode object at 0x7fe680eba8d0>, <TextNode: u\'?page=\'>, <Variable Node: p.p_next>, <TextNode: u\'">&raquo;</a></li>\\n      \'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n              <!--<div c\'>, <For Node: for i in p2.p_content, tail_len: 27>, <TextNode: u\'\\n                        \'>, <Variable Node: p2.p_count>, <TextNode: u\'</span> \\u6761\\u8bb0\\u5f55\\uff0c\\u603b <span  clas\'>, <Variable Node: p2.p_pages>, <TextNode: u\'</span> \\u9875\\uff0c\\u5f53\\u524d\\u5728<span class=\'>, <Variable Node: p2.page>, <TextNode: u\'</span>\\u9875\\n                \'>, <django.template.defaulttags.URLNode object at 0x7fe680e6b790>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_previous>, <TextNode: u\'">&laquo;</a></li>\\n      \'>, <django.template.defaulttags.URLNode object at 0x7fe680e6b950>, <TextNode: u\'?page2=1">\\u9996\\u9875</a></li>\\n   \'>, <For Node: for i in p2.p_range, tail_len: 9>, <TextNode: u\'\\n                        \'>, <django.template.defaulttags.URLNode object at 0x7fe680e6bf50>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_pages>, <TextNode: u\'">\\u5c3e\\u9875</a></li>\\n           \'>, <django.template.defaulttags.URLNode object at 0x7fe680e71150>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_next>, <TextNode: u\'">&raquo;</a></li>\\n      \'>]>}, {}]'
2017-08-28 12:46:45,068 [Thread-7:140627991459584] [django.template:927] [DEBUG]- Exception while resolving variable 'page' in template 'crawlermanage/tasks.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [page] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fe680e74050>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fe680ef2a28>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fe680ef8dd0>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fe680ef8190>, u\'request\': <WSGIRequest: GET \'/crawlermanage/tasks/\'>}, {}, {\'p2\': <crawlermanage.utils.page.paging instance at 0x7fe680ed6b00>, \'status\': \'currenttask\', \'pausing_count\': 4, \'error_count\': 0, \'p\': <crawlermanage.utils.page.paging instance at 0x7fe680f97fc8>, \'running_count\': 3, \'stopping_count\': 4}, {\'block\': <Block Node: script. Contents: [<TextNode: u\'\\n<script src="../../stati\'>, <Variable Node: page>, <TextNode: u\'"\\n                  if(pa\'>]>}]'
2017-08-28 12:47:07,311 [Thread-8:140627991459584] [crawlermanage.views:262] [INFO]- 59a2d3879c1da947bb188cb2
2017-08-28 12:47:07,316 [Thread-8:140627991459584] [crawlermanage.views:265] [INFO]- running
2017-08-28 12:47:26,519 [Thread-15:140627991459584] [crawlermanage.views:102] [INFO]- [<Task: Task object>]
2017-08-28 12:47:26,663 [Thread-17:140627991459584] [django.template:927] [DEBUG]- Exception while resolving variable 'tasklist' in template 'crawlermanage/tasks.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [tasklist] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fe680ea52a8>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fe680ef2c80>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fe680eeb1d0>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fe680f69c90>, u\'request\': <WSGIRequest: GET \'/crawlermanage/tasks/?page=1\'>}, {}, {\'p2\': <crawlermanage.utils.page.paging instance at 0x7fe680eadb00>, \'status\': \'currenttask\', \'pausing_count\': 4, \'error_count\': 0, \'p\': <crawlermanage.utils.page.paging instance at 0x7fe680ead680>, \'running_count\': 2, \'stopping_count\': 5}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n\\n\\n<!--<div class="box">-\'>, <Variable Node: running_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: pausing_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: stopping_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: error_count>, <TextNode: u\'</span>\\n            </div\'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n\\n            </ul>\\n     \'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n\\n\\n\\n                  <di\'>, <For Node: for task in tasklist, tail_len: 11>, <TextNode: u\'\\n\\t\\t\\t                \\n  \\t\\t\'>, <For Node: for i in p.p_content, tail_len: 33>, <TextNode: u\'\\n                        \'>, <Variable Node: p.p_count>, <TextNode: u\'</span> \\u6761\\u8bb0\\u5f55\\uff0c\\u603b <span  clas\'>, <Variable Node: p.p_pages>, <TextNode: u\'</span> \\u9875\\uff0c\\u5f53\\u524d\\u5728<span class=\'>, <Variable Node: p.page>, <TextNode: u\'</span>\\u9875\\n                \'>, <django.template.defaulttags.URLNode object at 0x7fe680e7f050>, <TextNode: u\'?page=\'>, <Variable Node: p.p_previous>, <TextNode: u\'">&laquo;</a></li>\\n      \'>, <django.template.defaulttags.URLNode object at 0x7fe680e7f210>, <TextNode: u\'?page=1">\\u9996\\u9875</a></li>\\n    \'>, <For Node: for i in p.p_range, tail_len: 9>, <TextNode: u\'\\n                        \'>, <django.template.defaulttags.URLNode object at 0x7fe680e7f810>, <TextNode: u\'?page=\'>, <Variable Node: p.p_pages>, <TextNode: u\'">\\u5c3e\\u9875</a></li>\\n           \'>, <django.template.defaulttags.URLNode object at 0x7fe680e7f9d0>, <TextNode: u\'?page=\'>, <Variable Node: p.p_next>, <TextNode: u\'">&raquo;</a></li>\\n      \'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n              <!--<div c\'>, <For Node: for i in p2.p_content, tail_len: 27>, <TextNode: u\'\\n                        \'>, <Variable Node: p2.p_count>, <TextNode: u\'</span> \\u6761\\u8bb0\\u5f55\\uff0c\\u603b <span  clas\'>, <Variable Node: p2.p_pages>, <TextNode: u\'</span> \\u9875\\uff0c\\u5f53\\u524d\\u5728<span class=\'>, <Variable Node: p2.page>, <TextNode: u\'</span>\\u9875\\n                \'>, <django.template.defaulttags.URLNode object at 0x7fe680e90890>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_previous>, <TextNode: u\'">&laquo;</a></li>\\n      \'>, <django.template.defaulttags.URLNode object at 0x7fe680e90a50>, <TextNode: u\'?page2=1">\\u9996\\u9875</a></li>\\n   \'>, <For Node: for i in p2.p_range, tail_len: 9>, <TextNode: u\'\\n                        \'>, <django.template.defaulttags.URLNode object at 0x7fe680e960d0>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_pages>, <TextNode: u\'">\\u5c3e\\u9875</a></li>\\n           \'>, <django.template.defaulttags.URLNode object at 0x7fe680e962d0>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_next>, <TextNode: u\'">&raquo;</a></li>\\n      \'>]>}, {}]'
2017-08-28 12:47:26,709 [Thread-17:140627991459584] [django.template:927] [DEBUG]- Exception while resolving variable 'page' in template 'crawlermanage/tasks.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [page] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fe680ea52a8>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fe680ef2c80>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fe680eeb1d0>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fe680f69c90>, u\'request\': <WSGIRequest: GET \'/crawlermanage/tasks/?page=1\'>}, {}, {\'p2\': <crawlermanage.utils.page.paging instance at 0x7fe680eadb00>, \'status\': \'currenttask\', \'pausing_count\': 4, \'error_count\': 0, \'p\': <crawlermanage.utils.page.paging instance at 0x7fe680ead680>, \'running_count\': 2, \'stopping_count\': 5}, {\'block\': <Block Node: script. Contents: [<TextNode: u\'\\n<script src="../../stati\'>, <Variable Node: page>, <TextNode: u\'"\\n                  if(pa\'>]>}]'
2017-08-28 12:47:33,591 [Thread-18:140627991459584] [django.template:927] [DEBUG]- Exception while resolving variable 'error1' in template 'crawlermanage/layout.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error1] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'ips\': [<Machine: Machine object>, <Machine: Machine object>, <Machine: Machine object>]}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n<div class="box box-prim\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fe680e90650>, <TextNode: u\'-->\\n              <!-- te\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <Variable Node: error2>, <TextNode: u\'</p>\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <For Node: for i in ips, tail_len: 5>, <TextNode: u\'\\n                        \'>]>}]'
2017-08-28 12:47:33,595 [Thread-18:140627991459584] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/layout.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'ips\': [<Machine: Machine object>, <Machine: Machine object>, <Machine: Machine object>]}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n<div class="box box-prim\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fe680e90650>, <TextNode: u\'-->\\n              <!-- te\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <Variable Node: error2>, <TextNode: u\'</p>\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <For Node: for i in ips, tail_len: 5>, <TextNode: u\'\\n                        \'>]>}]'
2017-08-28 12:47:33,595 [Thread-18:140627991459584] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/layout.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'ips\': [<Machine: Machine object>, <Machine: Machine object>, <Machine: Machine object>]}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n<div class="box box-prim\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fe680e90650>, <TextNode: u\'-->\\n              <!-- te\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <Variable Node: error2>, <TextNode: u\'</p>\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <For Node: for i in ips, tail_len: 5>, <TextNode: u\'\\n                        \'>]>}]'
2017-08-28 12:47:33,596 [Thread-18:140627991459584] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/layout.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'ips\': [<Machine: Machine object>, <Machine: Machine object>, <Machine: Machine object>]}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n<div class="box box-prim\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fe680e90650>, <TextNode: u\'-->\\n              <!-- te\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <Variable Node: error2>, <TextNode: u\'</p>\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <For Node: for i in ips, tail_len: 5>, <TextNode: u\'\\n                        \'>]>}]'
2017-08-28 12:47:38,587 [Thread-20:140627991459584] [django.template:927] [DEBUG]- Exception while resolving variable 'page' in template 'crawlermanage/process_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [page] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fe680ef2f50>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fe680ef2e60>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fe680ef1f50>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fe680ef1590>, u\'request\': <WSGIRequest: GET \'/crawlermanage/processlist/\'>}, {}, {\'p\': <crawlermanage.utils.page.paging instance at 0x7fe680ea6710>, \'pc_name\': []}, {\'block\': <Block Node: script. Contents: [<TextNode: u\'\\n<script src="../../stati\'>, <Variable Node: page>, <TextNode: u\'"\\n                  if(pa\'>, <Variable Node: page>, <TextNode: u\'"\\n                  if(pa\'>]>}]'
2017-08-28 12:47:38,588 [Thread-20:140627991459584] [django.template:927] [DEBUG]- Exception while resolving variable 'page' in template 'crawlermanage/process_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [page] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fe680ef2f50>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fe680ef2e60>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fe680ef1f50>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fe680ef1590>, u\'request\': <WSGIRequest: GET \'/crawlermanage/processlist/\'>}, {}, {\'p\': <crawlermanage.utils.page.paging instance at 0x7fe680ea6710>, \'pc_name\': []}, {\'block\': <Block Node: script. Contents: [<TextNode: u\'\\n<script src="../../stati\'>, <Variable Node: page>, <TextNode: u\'"\\n                  if(pa\'>, <Variable Node: page>, <TextNode: u\'"\\n                  if(pa\'>]>}]'
2017-08-28 12:48:15,051 [Thread-25:140627991459584] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:48:15,576 [Thread-27:140627991459584] [crawlermanage.views:561] [INFO]- true
2017-08-28 12:48:18,501 [Thread-29:140627991459584] [django.template:927] [DEBUG]- Exception while resolving variable 'error1' in template 'crawlermanage/layout.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error1] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'ips\': [<Machine: Machine object>, <Machine: Machine object>, <Machine: Machine object>]}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n<div class="box box-prim\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fe680e90250>, <TextNode: u\'-->\\n              <!-- te\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <Variable Node: error2>, <TextNode: u\'</p>\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <For Node: for i in ips, tail_len: 5>, <TextNode: u\'\\n                        \'>]>}]'
2017-08-28 12:48:18,506 [Thread-29:140627991459584] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/layout.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'ips\': [<Machine: Machine object>, <Machine: Machine object>, <Machine: Machine object>]}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n<div class="box box-prim\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fe680e90250>, <TextNode: u\'-->\\n              <!-- te\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <Variable Node: error2>, <TextNode: u\'</p>\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <For Node: for i in ips, tail_len: 5>, <TextNode: u\'\\n                        \'>]>}]'
2017-08-28 12:48:18,506 [Thread-29:140627991459584] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/layout.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'ips\': [<Machine: Machine object>, <Machine: Machine object>, <Machine: Machine object>]}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n<div class="box box-prim\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fe680e90250>, <TextNode: u\'-->\\n              <!-- te\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <Variable Node: error2>, <TextNode: u\'</p>\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <For Node: for i in ips, tail_len: 5>, <TextNode: u\'\\n                        \'>]>}]'
2017-08-28 12:48:18,507 [Thread-29:140627991459584] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/layout.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'ips\': [<Machine: Machine object>, <Machine: Machine object>, <Machine: Machine object>]}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n<div class="box box-prim\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fe680e90250>, <TextNode: u\'-->\\n              <!-- te\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <Variable Node: error2>, <TextNode: u\'</p>\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <For Node: for i in ips, tail_len: 5>, <TextNode: u\'\\n                        \'>]>}]'
2017-08-28 12:48:41,681 [Thread-30:140627991459584] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-28 12:48:42,385 [Thread-32:140627991459584] [crawlermanage.views:561] [INFO]- true
