2017-08-27 14:15:28,771 [Dummy-1:140685584279296] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-27 14:15:28,774 [Dummy-1:140685584279296] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-27 14:16:49,927 [Dummy-1:139708937410304] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-27 14:16:49,933 [Dummy-1:139708937410304] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-27 14:16:55,151 [Thread-2:139708695152384] [crawlermanage.views:544] [INFO]- vdfgdf#iouyi#iuo
2017-08-27 14:17:39,004 [Dummy-1:140592043480832] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-27 14:17:39,007 [Dummy-1:140592043480832] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-27 14:23:19,218 [Thread-2:140591795009280] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-27 14:23:39,280 [Thread-8:140591753045760] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-27 14:25:44,590 [Dummy-1:140611592124160] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-27 14:25:44,601 [Dummy-1:140611592124160] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-27 14:26:05,717 [Dummy-1:140635538626304] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-27 14:26:05,720 [Dummy-1:140635538626304] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-27 14:26:07,997 [Thread-2:140635499521792] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-27 14:26:36,837 [Dummy-1:139879747544832] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-27 14:26:36,839 [Dummy-1:139879747544832] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-27 14:26:38,482 [Thread-2:139879501526784] [crawlermanage.views:545] [INFO]- ggdf#dfg
2017-08-27 14:26:38,482 [Thread-2:139879501526784] [crawlermanage.views:550] [INFO]- ggdf#dfg
2017-08-27 14:26:38,486 [Thread-2:139879501526784] [crawlermanage.views:551] [INFO]- ggdf#dfg
2017-08-27 14:27:06,823 [Dummy-1:139946027779840] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-27 14:27:06,829 [Dummy-1:139946027779840] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-27 14:27:12,876 [Thread-2:139945785546496] [crawlermanage.views:545] [INFO]- true
2017-08-27 14:27:12,877 [Thread-2:139945785546496] [crawlermanage.views:546] [INFO]- ggdf#dfg
2017-08-27 14:27:12,877 [Thread-2:139945785546496] [crawlermanage.views:551] [INFO]- 1
2017-08-27 14:27:43,031 [Dummy-1:140006224520960] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-27 14:27:43,033 [Dummy-1:140006224520960] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-27 14:27:46,428 [Thread-2:140005982459648] [crawlermanage.views:545] [INFO]- <type 'unicode'>
2017-08-27 14:27:46,429 [Thread-2:140005982459648] [crawlermanage.views:546] [INFO]- ggdf#dfg
2017-08-27 14:27:46,429 [Thread-2:140005982459648] [crawlermanage.views:551] [INFO]- 1
2017-08-27 14:34:40,105 [Dummy-1:140531396769536] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-27 14:34:40,108 [Dummy-1:140531396769536] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-27 14:34:41,181 [Thread-2:140531356092160] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-27 14:35:22,165 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-27 14:35:22,169 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-27 14:35:22,170 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-27 14:35:22,173 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-27 14:35:22,252 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'logentry' AND "django_content_type"."app_label" = 'admin'); args=('logentry', 'admin')
2017-08-27 14:35:22,260 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (1) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(1,)
2017-08-27 14:35:22,262 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'admin'; args=('admin',)
2017-08-27 14:35:22,263 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'permission' AND "django_content_type"."app_label" = 'auth'); args=('permission', 'auth')
2017-08-27 14:35:22,267 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'group' AND "django_content_type"."app_label" = 'auth'); args=('group', 'auth')
2017-08-27 14:35:22,269 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'user' AND "django_content_type"."app_label" = 'auth'); args=('user', 'auth')
2017-08-27 14:35:22,274 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (2, 3, 4) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(2, 3, 4)
2017-08-27 14:35:22,276 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'auth'; args=('auth',)
2017-08-27 14:35:22,277 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'contenttype' AND "django_content_type"."app_label" = 'contenttypes'); args=('contenttype', 'contenttypes')
2017-08-27 14:35:22,280 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (5) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(5,)
2017-08-27 14:35:22,281 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'contenttypes'; args=('contenttypes',)
2017-08-27 14:35:22,282 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'session' AND "django_content_type"."app_label" = 'sessions'); args=('session', 'sessions')
2017-08-27 14:35:22,290 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (6) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(6,)
2017-08-27 14:35:22,291 [MainThread:140229015828224] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'sessions'; args=('sessions',)
2017-08-27 14:35:30,177 [Dummy-1:140456988780288] [django.db.backends:89] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-27 14:35:30,180 [Dummy-1:140456988780288] [django.db.backends:89] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-27 14:35:37,471 [Thread-2:140456746583808] [django.template:927] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/settings.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n      <div class="box bo\'>, <IfNode>, <TextNode: u\' -->\\n                  <b\'>]>}]'
2017-08-27 14:36:22,534 [Thread-8:140456495146752] [crawlermanage.views:545] [INFO]- <type 'unicode'>
2017-08-27 14:36:22,534 [Thread-8:140456495146752] [crawlermanage.views:546] [INFO]- http://119.125.53.23:8080#http://192.168.1.110:80
2017-08-28 18:15:44,269 [Dummy-1:140332746811136] [django.db.backends:91] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-08-28 18:15:44,271 [Dummy-1:140332746811136] [django.db.backends:91] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-08-28 18:15:57,112 [Thread-2:140332698789632] [django.server:124] [INFO]- "GET /crawlermanage HTTP/1.1" 301 0
2017-08-28 18:15:57,122 [Thread-3:140332553467648] [django.template:925] [DEBUG]- Exception while resolving variable 'error' in template 'crawlermanage/login.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error] in u"[{'False': False, 'None': None, 'True': True}]"
2017-08-28 18:15:57,125 [Thread-3:140332553467648] [django.server:124] [INFO]- "GET /crawlermanage/ HTTP/1.1" 200 2068
2017-08-28 18:15:57,162 [Thread-5:140332698789632] [django.server:124] [INFO]- "GET /static/plugins/jQuery/jquery-2.2.3.min.js HTTP/1.1" 200 85659
2017-08-28 18:15:57,163 [Thread-4:140332553467648] [django.server:124] [INFO]- "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 200 121200
2017-08-28 18:15:57,164 [Thread-6:140332545074944] [django.server:124] [INFO]- "GET /static/bootstrap/js/bootstrap.min.js HTTP/1.1" 200 37045
2017-08-28 18:15:57,569 [Thread-7:140332545074944] [django.template:925] [DEBUG]- Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
2017-08-28 18:15:57,575 [Thread-7:140332545074944] [django.server:124] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5859
2017-08-28 18:16:03,700 [Thread-8:140332545074944] [django.server:124] [INFO]- "POST /crawlermanage/login/ HTTP/1.1" 302 0
2017-08-28 18:16:03,704 [Thread-9:140332545074944] [django.server:124] [INFO]- "GET /crawlermanage/index HTTP/1.1" 301 0
2017-08-28 18:16:03,721 [Thread-10:140332545074944] [django.server:124] [INFO]- "GET /crawlermanage/index/ HTTP/1.1" 200 10251
2017-08-28 18:16:03,731 [Thread-11:140332545074944] [django.server:124] [INFO]- "GET /static/style/font-awesome/css/font-awesome.min.css HTTP/1.1" 200 31000
2017-08-28 18:16:03,741 [Thread-14:140332698789632] [django.server:124] [INFO]- "GET /static/plugins/iCheck/flat/blue.css HTTP/1.1" 200 1428
2017-08-28 18:16:03,741 [Thread-12:140332553467648] [django.server:124] [INFO]- "GET /static/dist/css/AdminLTE.min.css HTTP/1.1" 200 90390
2017-08-28 18:16:03,742 [Thread-13:140332545074944] [django.server:124] [INFO]- "GET /static/dist/css/skins/_all-skins.min.css HTTP/1.1" 200 40757
2017-08-28 18:16:03,750 [Thread-15:140332545074944] [django.server:124] [INFO]- "GET /static/dist/js/app.min.js HTTP/1.1" 200 9923
2017-08-28 18:16:03,774 [Thread-16:140332545074944] [django.server:124] [INFO]- "GET /static/dist/js/demo.js HTTP/1.1" 200 17319
2017-08-28 18:16:03,781 [Thread-17:140332698789632] [django.server:124] [INFO]- "GET /static/imgs/logo.png HTTP/1.1" 200 246359
2017-08-28 18:16:04,061 [Thread-18:140332698789632] [django.server:124] [INFO]- "GET /static/style/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 77160
2017-08-28 18:16:11,015 [Thread-19:140332698789632] [django.server:124] [INFO]- "GET /crawlermanage/extractmultiple/ HTTP/1.1" 200 19918
2017-08-28 18:16:11,034 [Thread-21:140332545074944] [django.server:124] [INFO]- "GET /static/plugins/daterangepicker/daterangepicker.css HTTP/1.1" 200 6666
2017-08-28 18:16:11,037 [Thread-20:140332698789632] [django.server:124] [INFO]- "GET /static/plugins/datatables/dataTables.bootstrap.css HTTP/1.1" 200 8829
2017-08-28 18:16:11,040 [Thread-22:140332553467648] [django.server:124] [INFO]- "GET /static/plugins/select2/select2.min.css HTTP/1.1" 200 15196
2017-08-28 18:17:04,755 [Thread-24:140332698789632] [django.server:124] [INFO]- "GET /static/bootstrap/css/bootstrap.min.css.map HTTP/1.1" 200 542194
2017-08-28 18:17:27,739 [Thread-23:140332553467648] [django.server:124] [INFO]- "POST /crawlermanage/extractmultiple/ HTTP/1.1" 200 103897
2017-08-28 18:18:21,169 [Thread-25:140332553467648] [django.server:124] [INFO]- "POST /crawlermanage/extractmultiple/ HTTP/1.1" 200 18624
2017-08-28 18:22:13,888 [Thread-26:140332553467648] [django.server:124] [INFO]- "POST /crawlermanage/extractmultiple/ HTTP/1.1" 200 39124
2017-08-28 18:24:36,550 [Thread-27:140332553467648] [django.server:124] [INFO]- "POST /crawlermanage/extractmultiple/ HTTP/1.1" 200 704
2017-08-28 18:26:03,287 [Thread-28:140332553467648] [django.server:124] [INFO]- "POST /crawlermanage/extractmultiple/ HTTP/1.1" 200 704
2017-08-28 19:34:56,634 [Thread-29:140332553467648] [django.server:124] [INFO]- "GET /crawlermanage/extractmultiple/ HTTP/1.1" 200 19918
2017-08-28 19:35:00,639 [Thread-30:140332553467648] [django.server:124] [INFO]- "GET /crawlermanage/extractsinger/ HTTP/1.1" 200 8350
2017-08-28 19:35:02,967 [Thread-31:140332553467648] [django.server:124] [INFO]- "POST /crawlermanage/extractsinger/ HTTP/1.1" 200 13254
2017-08-28 20:21:38,911 [Thread-32:140332553467648] [django.server:124] [INFO]- "GET /crawlermanage/extractmultiple/ HTTP/1.1" 200 19918
2017-08-28 20:21:47,167 [Thread-33:140332553467648] [django.server:124] [INFO]- "POST /crawlermanage/extractmultiple/ HTTP/1.1" 200 6953
2017-08-28 20:23:07,143 [Thread-34:140332553467648] [django.server:124] [ERROR]- "POST /crawlermanage/extractmultiple/ HTTP/1.1" 500 24097
2017-08-28 20:23:16,565 [Thread-35:140332553467648] [django.server:124] [INFO]- "GET /crawlermanage/extractmultiple/ HTTP/1.1" 200 19918
2017-08-28 20:23:28,240 [Thread-36:140332553467648] [django.server:124] [INFO]- "POST /crawlermanage/extractmultiple/ HTTP/1.1" 200 7494
2017-08-28 20:26:29,073 [Thread-37:140332553467648] [django.server:124] [INFO]- "POST /crawlermanage/extractmultiple/ HTTP/1.1" 200 1052
2017-08-28 20:26:52,236 [Thread-38:140332553467648] [django.server:124] [INFO]- "POST /crawlermanage/extractmultiple/ HTTP/1.1" 200 1052
2017-08-28 20:35:50,235 [Thread-39:140332553467648] [django.template:925] [DEBUG]- Exception while resolving variable 'tasklist' in template 'crawlermanage/tasks.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [tasklist] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fa1b5a7b488>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fa1b5a7b758>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fa1b57e84d0>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fa1c0108f10>, u\'request\': <WSGIRequest: GET \'/crawlermanage/tasks/\'>}, {}, {\'p2\': <crawlermanage.utils.page.paging instance at 0x7fa1b5f60200>, \'status\': \'currenttask\', \'pausing_count\': 4, \'error_count\': 0, \'p\': <crawlermanage.utils.page.paging instance at 0x7fa1b5f60320>, \'running_count\': 3, \'stopping_count\': 4}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n\\n\\n<!--<div class="box">-\'>, <Variable Node: running_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: pausing_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: stopping_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: error_count>, <TextNode: u\'</span>\\n            </div\'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n\\n            </ul>\\n     \'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n\\n\\n\\n                  <di\'>, <For Node: for task in tasklist, tail_len: 11>, <TextNode: u\'\\n\\t\\t\\t                \\n  \\t\\t\'>, <For Node: for i in p.p_content, tail_len: 33>, <TextNode: u\'\\n                        \'>, <Variable Node: p.p_count>, <TextNode: u\'</span> \\u6761\\u8bb0\\u5f55\\uff0c\\u603b <span  clas\'>, <Variable Node: p.p_pages>, <TextNode: u\'</span> \\u9875\\uff0c\\u5f53\\u524d\\u5728<span class=\'>, <Variable Node: p.page>, <TextNode: u\'</span>\\u9875\\n                \'>, <django.template.defaulttags.URLNode object at 0x7fa1b618eb10>, <TextNode: u\'?page=\'>, <Variable Node: p.p_previous>, <TextNode: u\'">&laquo;</a></li>\\n      \'>, <django.template.defaulttags.URLNode object at 0x7fa1b618e6d0>, <TextNode: u\'?page=1">\\u9996\\u9875</a></li>\\n    \'>, <For Node: for i in p.p_range, tail_len: 9>, <TextNode: u\'\\n                        \'>, <django.template.defaulttags.URLNode object at 0x7fa1c0d28690>, <TextNode: u\'?page=\'>, <Variable Node: p.p_pages>, <TextNode: u\'">\\u5c3e\\u9875</a></li>\\n           \'>, <django.template.defaulttags.URLNode object at 0x7fa1c0d28f10>, <TextNode: u\'?page=\'>, <Variable Node: p.p_next>, <TextNode: u\'">&raquo;</a></li>\\n      \'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n              <!--<div c\'>, <For Node: for i in p2.p_content, tail_len: 27>, <TextNode: u\'\\n                        \'>, <Variable Node: p2.p_count>, <TextNode: u\'</span> \\u6761\\u8bb0\\u5f55\\uff0c\\u603b <span  clas\'>, <Variable Node: p2.p_pages>, <TextNode: u\'</span> \\u9875\\uff0c\\u5f53\\u524d\\u5728<span class=\'>, <Variable Node: p2.page>, <TextNode: u\'</span>\\u9875\\n                \'>, <django.template.defaulttags.URLNode object at 0x7fa1b633fa10>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_previous>, <TextNode: u\'">&laquo;</a></li>\\n      \'>, <django.template.defaulttags.URLNode object at 0x7fa1b633f690>, <TextNode: u\'?page2=1">\\u9996\\u9875</a></li>\\n   \'>, <For Node: for i in p2.p_range, tail_len: 9>, <TextNode: u\'\\n                        \'>, <django.template.defaulttags.URLNode object at 0x7fa1b633f250>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_pages>, <TextNode: u\'">\\u5c3e\\u9875</a></li>\\n           \'>, <django.template.defaulttags.URLNode object at 0x7fa1c3905050>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_next>, <TextNode: u\'">&raquo;</a></li>\\n      \'>]>}, {}]'
2017-08-28 20:35:50,249 [Thread-39:140332553467648] [django.template:925] [DEBUG]- Exception while resolving variable 'page' in template 'crawlermanage/tasks.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [page] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fa1b5a7b488>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fa1b5a7b758>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fa1b57e84d0>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fa1c0108f10>, u\'request\': <WSGIRequest: GET \'/crawlermanage/tasks/\'>}, {}, {\'p2\': <crawlermanage.utils.page.paging instance at 0x7fa1b5f60200>, \'status\': \'currenttask\', \'pausing_count\': 4, \'error_count\': 0, \'p\': <crawlermanage.utils.page.paging instance at 0x7fa1b5f60320>, \'running_count\': 3, \'stopping_count\': 4}, {\'block\': <Block Node: script. Contents: [<TextNode: u\'\\n<script src="../../stati\'>, <Variable Node: page>, <TextNode: u\'"\\n                  if(pa\'>]>}]'
2017-08-28 20:35:50,250 [Thread-39:140332553467648] [django.server:124] [INFO]- "GET /crawlermanage/tasks/ HTTP/1.1" 200 34317
2017-08-28 20:35:50,263 [Thread-40:140332553467648] [django.server:124] [INFO]- "GET /static/plugins/bootstrap3-editable/css/bootstrap-editable.css HTTP/1.1" 200 21202
2017-08-28 20:35:50,269 [Thread-41:140332698789632] [django.server:124] [INFO]- "GET /static/plugins/datatables/jquery.dataTables.min.js HTTP/1.1" 200 79881
2017-08-28 20:35:50,273 [Thread-42:140332698789632] [django.server:124] [INFO]- "GET /static/plugins/datatables/dataTables.bootstrap.min.js HTTP/1.1" 200 2065
2017-08-28 20:35:50,279 [Thread-43:140332698789632] [django.server:124] [INFO]- "GET /static/plugins/bootstrap3-editable/js/bootstrap-editable.min.js HTTP/1.1" 200 75909
2017-08-28 20:35:53,824 [Thread-44:140332698789632] [django.template:925] [DEBUG]- Exception while resolving variable 'tasklist' in template 'crawlermanage/tasks.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [tasklist] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fa1b5a7b488>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fa1c0148230>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fa1b58bde50>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fa1b5f7da10>, u\'request\': <WSGIRequest: GET \'/crawlermanage/tasks/\'>}, {}, {\'p2\': <crawlermanage.utils.page.paging instance at 0x7fa1b5d43ab8>, \'status\': \'currenttask\', \'pausing_count\': 4, \'error_count\': 0, \'p\': <crawlermanage.utils.page.paging instance at 0x7fa1b6333638>, \'running_count\': 3, \'stopping_count\': 4}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n\\n\\n<!--<div class="box">-\'>, <Variable Node: running_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: pausing_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: stopping_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: error_count>, <TextNode: u\'</span>\\n            </div\'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n\\n            </ul>\\n     \'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n\\n\\n\\n                  <di\'>, <For Node: for task in tasklist, tail_len: 11>, <TextNode: u\'\\n\\t\\t\\t                \\n  \\t\\t\'>, <For Node: for i in p.p_content, tail_len: 33>, <TextNode: u\'\\n                        \'>, <Variable Node: p.p_count>, <TextNode: u\'</span> \\u6761\\u8bb0\\u5f55\\uff0c\\u603b <span  clas\'>, <Variable Node: p.p_pages>, <TextNode: u\'</span> \\u9875\\uff0c\\u5f53\\u524d\\u5728<span class=\'>, <Variable Node: p.page>, <TextNode: u\'</span>\\u9875\\n                \'>, <django.template.defaulttags.URLNode object at 0x7fa1b6625890>, <TextNode: u\'?page=\'>, <Variable Node: p.p_previous>, <TextNode: u\'">&laquo;</a></li>\\n      \'>, <django.template.defaulttags.URLNode object at 0x7fa1b66257d0>, <TextNode: u\'?page=1">\\u9996\\u9875</a></li>\\n    \'>, <For Node: for i in p.p_range, tail_len: 9>, <TextNode: u\'\\n                        \'>, <django.template.defaulttags.URLNode object at 0x7fa1c026e090>, <TextNode: u\'?page=\'>, <Variable Node: p.p_pages>, <TextNode: u\'">\\u5c3e\\u9875</a></li>\\n           \'>, <django.template.defaulttags.URLNode object at 0x7fa1b6185dd0>, <TextNode: u\'?page=\'>, <Variable Node: p.p_next>, <TextNode: u\'">&raquo;</a></li>\\n      \'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n              <!--<div c\'>, <For Node: for i in p2.p_content, tail_len: 27>, <TextNode: u\'\\n                        \'>, <Variable Node: p2.p_count>, <TextNode: u\'</span> \\u6761\\u8bb0\\u5f55\\uff0c\\u603b <span  clas\'>, <Variable Node: p2.p_pages>, <TextNode: u\'</span> \\u9875\\uff0c\\u5f53\\u524d\\u5728<span class=\'>, <Variable Node: p2.page>, <TextNode: u\'</span>\\u9875\\n                \'>, <django.template.defaulttags.URLNode object at 0x7fa1b544b150>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_previous>, <TextNode: u\'">&laquo;</a></li>\\n      \'>, <django.template.defaulttags.URLNode object at 0x7fa1b544b310>, <TextNode: u\'?page2=1">\\u9996\\u9875</a></li>\\n   \'>, <For Node: for i in p2.p_range, tail_len: 9>, <TextNode: u\'\\n                        \'>, <django.template.defaulttags.URLNode object at 0x7fa1b544b910>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_pages>, <TextNode: u\'">\\u5c3e\\u9875</a></li>\\n           \'>, <django.template.defaulttags.URLNode object at 0x7fa1b544bad0>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_next>, <TextNode: u\'">&raquo;</a></li>\\n      \'>]>}, {}]'
2017-08-28 20:35:53,835 [Thread-44:140332698789632] [django.template:925] [DEBUG]- Exception while resolving variable 'page' in template 'crawlermanage/tasks.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [page] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fa1b5a7b488>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fa1c0148230>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fa1b58bde50>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fa1b5f7da10>, u\'request\': <WSGIRequest: GET \'/crawlermanage/tasks/\'>}, {}, {\'p2\': <crawlermanage.utils.page.paging instance at 0x7fa1b5d43ab8>, \'status\': \'currenttask\', \'pausing_count\': 4, \'error_count\': 0, \'p\': <crawlermanage.utils.page.paging instance at 0x7fa1b6333638>, \'running_count\': 3, \'stopping_count\': 4}, {\'block\': <Block Node: script. Contents: [<TextNode: u\'\\n<script src="../../stati\'>, <Variable Node: page>, <TextNode: u\'"\\n                  if(pa\'>]>}]'
2017-08-28 20:35:53,836 [Thread-44:140332698789632] [django.server:124] [INFO]- "GET /crawlermanage/tasks/ HTTP/1.1" 200 34317
2017-08-28 20:35:57,553 [Thread-45:140332553467648] [django.template:925] [DEBUG]- Exception while resolving variable 'error1' in template 'crawlermanage/layout.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error1] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'ips\': [<Machine: Machine object>, <Machine: Machine object>, <Machine: Machine object>]}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n<div class="box box-prim\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fa1c0cda7d0>, <TextNode: u\'-->\\n              <!-- te\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <Variable Node: error2>, <TextNode: u\'</p>\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <For Node: for i in ips, tail_len: 5>, <TextNode: u\'\\n                        \'>]>}]'
2017-08-28 20:35:57,554 [Thread-45:140332553467648] [django.template:925] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/layout.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'ips\': [<Machine: Machine object>, <Machine: Machine object>, <Machine: Machine object>]}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n<div class="box box-prim\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fa1c0cda7d0>, <TextNode: u\'-->\\n              <!-- te\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <Variable Node: error2>, <TextNode: u\'</p>\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <For Node: for i in ips, tail_len: 5>, <TextNode: u\'\\n                        \'>]>}]'
2017-08-28 20:35:57,555 [Thread-45:140332553467648] [django.template:925] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/layout.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'ips\': [<Machine: Machine object>, <Machine: Machine object>, <Machine: Machine object>]}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n<div class="box box-prim\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fa1c0cda7d0>, <TextNode: u\'-->\\n              <!-- te\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <Variable Node: error2>, <TextNode: u\'</p>\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <For Node: for i in ips, tail_len: 5>, <TextNode: u\'\\n                        \'>]>}]'
2017-08-28 20:35:57,555 [Thread-45:140332553467648] [django.template:925] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/layout.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'ips\': [<Machine: Machine object>, <Machine: Machine object>, <Machine: Machine object>]}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n<div class="box box-prim\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fa1c0cda7d0>, <TextNode: u\'-->\\n              <!-- te\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <Variable Node: error2>, <TextNode: u\'</p>\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <For Node: for i in ips, tail_len: 5>, <TextNode: u\'\\n                        \'>]>}]'
2017-08-28 20:35:57,558 [Thread-45:140332553467648] [django.server:124] [INFO]- "GET /crawlermanage/layout/ HTTP/1.1" 200 16507
2017-08-28 20:35:57,603 [Thread-46:140332553467648] [django.server:124] [INFO]- "GET /static/plugins/select2/select2.full.min.js HTTP/1.1" 200 75005
2017-08-28 20:35:57,631 [Thread-47:140332553467648] [django.server:124] [INFO]- "GET /static/plugins/bootstrap3-editable/js/moment.js HTTP/1.1" 200 51465
2017-08-28 20:35:57,633 [Thread-48:140332698789632] [django.server:124] [INFO]- "GET /static/plugins/daterangepicker/daterangepicker.js HTTP/1.1" 200 64795
