2017-05-18 16:13:16,433 [Thread-3:139949737649920] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-18 16:13:18,312 [Thread-5:139949720864512] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-18 16:13:20,020 [Thread-7:139949720864512] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:13:25,893 [Thread-9:139949720864512] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:14:09,685 [Thread-3:139751237568256] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-18 16:14:11,691 [Thread-5:139751237568256] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:14:18,167 [Thread-7:139751237568256] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:15:00,329 [Thread-9:139751237568256] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:16:03,666 [Thread-3:140297441978112] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-18 16:16:06,998 [Thread-5:140297441978112] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:16:12,213 [Thread-7:140297441978112] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:16:47,085 [Thread-9:140297441978112] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:16:47,663 [Thread-11:140297441978112] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:16:56,313 [Thread-13:140297441978112] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:16:58,107 [Thread-15:140297441978112] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:18:00,447 [Thread-3:140355555165952] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:18:26,648 [Thread-5:140355555165952] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:18:54,290 [Thread-7:140355555165952] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-18 16:18:55,533 [Thread-9:140355555165952] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:19:12,679 [Thread-11:140355555165952] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:20:09,868 [Thread-3:139891504137984] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-18 16:20:11,195 [Thread-5:139891504137984] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:20:14,386 [Thread-7:139891504137984] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:20:44,850 [Thread-3:140032979498752] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-18 16:20:47,488 [Thread-5:140032979498752] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:20:50,306 [Thread-7:140032979498752] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:22:53,305 [Thread-3:140521226204928] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-18 16:22:54,473 [Thread-5:140521226204928] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:22:58,412 [Thread-7:140521226204928] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:23:43,532 [Thread-3:140362312660736] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-18 16:23:45,590 [Thread-5:140362312660736] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:23:48,587 [Thread-7:140362312660736] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:50:28,232 [Thread-3:140667894290176] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-18 16:50:29,605 [Thread-5:140667894290176] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:50:32,683 [Thread-7:140667894290176] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:51:10,390 [Thread-3:139894313334528] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:51:14,235 [Thread-5:139894313334528] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:51:20,197 [Thread-7:139894313334528] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:51:21,244 [Thread-9:139894313334528] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:51:21,924 [Thread-11:139894313334528] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:51:22,692 [Thread-13:139894313334528] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:51:23,484 [Thread-15:139894313334528] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:51:26,661 [Thread-16:139894313334528] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/pages/widgets.html
2017-05-18 16:51:28,949 [Thread-18:139894304155392] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:51:29,624 [Thread-20:139894287369984] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:51:30,226 [Thread-22:139893929932544] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:51:31,096 [Thread-24:139893929932544] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:53:16,520 [Thread-3:140550237099776] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:53:21,788 [Thread-5:140550237099776] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 16:54:36,131 [Thread-8:139999000733440] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-18 16:59:18,204 [Thread-22:139999000733440] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-18 17:02:37,396 [Thread-3:139844729706240] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:02:39,972 [Thread-5:139844729706240] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:02:40,476 [Thread-7:139844729706240] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:02:41,219 [Thread-9:139844729706240] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:02:41,854 [Thread-11:139844729706240] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:02:42,482 [Thread-13:139844729706240] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:02:43,223 [Thread-15:139844729706240] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:02:43,817 [Thread-17:139844729706240] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:03:13,741 [Thread-2:139769490319104] [django.request:256] [ERROR]- Internal Server Error: /crawlermanage/layout/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view crawlermanage.views.layout didn't return an HttpResponse object. It returned None instead.
2017-05-18 17:03:18,832 [Thread-7:139769490319104] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-18 17:03:20,050 [Thread-8:139769490319104] [django.request:256] [ERROR]- Internal Server Error: /crawlermanage/layout/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view crawlermanage.views.layout didn't return an HttpResponse object. It returned None instead.
2017-05-18 17:03:33,259 [Thread-3:139917946513152] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:04:06,525 [Thread-2:140413789443840] [django.request:256] [ERROR]- Internal Server Error: /crawlermanage/layout/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kui/work/python/project/geowind_crawler/crawlermanage/views.py", line 58, in layout
    return render_to_response(request, 'crawlermanage/layout.html')
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: <WSGIRequest: GET '/crawlermanage/layout/'>
2017-05-18 17:05:46,578 [Thread-5:140622272296704] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-18 17:05:47,864 [Thread-6:140622272296704] [django.request:256] [ERROR]- Internal Server Error: /crawlermanage/layout/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kui/work/python/project/geowind_crawler/crawlermanage/views.py", line 58, in layout
    return render_to_response(request, 'crawlermanage/layout.html')
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: <WSGIRequest: GET '/crawlermanage/layout/'>
2017-05-18 17:06:30,760 [Thread-7:140622272296704] [django.request:256] [ERROR]- Internal Server Error: /crawlermanage/layout/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kui/work/python/project/geowind_crawler/crawlermanage/views.py", line 58, in layout
    return render_to_response(request, 'crawlermanage/layout.html')
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: <WSGIRequest: GET '/crawlermanage/layout/'>
2017-05-18 17:07:44,658 [Thread-3:140648479360768] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:07:45,071 [Thread-5:140648470443776] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:07:45,903 [Thread-7:140648453658368] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:07:48,225 [Thread-9:140648099346176] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:07:49,713 [Thread-11:140648479360768] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:07:50,479 [Thread-13:140648479360768] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:07:52,442 [Thread-15:140648479360768] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-18 17:07:53,056 [Thread-17:140648479360768] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-18 17:07:54,251 [Thread-19:140648479360768] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:07:58,414 [Thread-21:140648479360768] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:08:12,021 [Thread-3:140373984220928] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:11:18,562 [Thread-7:139672487921408] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-18 17:11:20,099 [Thread-9:139672487921408] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:11:54,158 [Thread-11:139672487921408] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-18 17:11:55,167 [Thread-13:139672487921408] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:11:57,651 [Thread-15:139672487921408] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:12:05,550 [Thread-17:139672487921408] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:17:05,014 [Thread-3:140240860600064] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:17:06,695 [Thread-5:140240843814656] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:17:08,282 [Thread-6:140240835421952] [django.request:256] [ERROR]- Internal Server Error: /crawlermanage/layout/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kui/work/python/project/geowind_crawler/crawlermanage/views.py", line 55, in layout
    error1, error2 = None
TypeError: 'NoneType' object is not iterable
2017-05-18 17:17:28,349 [Thread-3:139717411305216] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:17:30,120 [Thread-5:139717394519808] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:17:31,509 [Thread-7:139717377734400] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:17:51,691 [Thread-9:139717377734400] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:17:52,921 [Thread-11:139717377734400] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:18:31,590 [Thread-20:139717394519808] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-18 17:18:32,646 [Thread-22:139717394519808] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:18:44,178 [Thread-26:139717402912512] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:19:35,334 [Thread-3:139818914924288] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-18 17:19:36,555 [Thread-4:139818914924288] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/pages/widgets.html
2017-05-18 17:19:39,085 [Thread-6:139818835113728] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:19:57,309 [Thread-15:139818809935616] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:21:07,197 [Thread-3:139652647769856] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:21:08,912 [Thread-5:139652647769856] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:22:25,248 [Thread-3:139962996639488] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:22:26,773 [Thread-5:139962996639488] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:22:29,098 [Thread-7:139962996639488] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:22:36,021 [Thread-9:139962996639488] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:23:00,397 [Thread-11:139962996639488] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:26:51,922 [Thread-13:139962917844736] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:26:53,438 [Thread-15:139962901059328] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:26:54,407 [Thread-17:139962884273920] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:27:09,335 [Thread-19:139962884273920] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:27:11,127 [Thread-21:139962884273920] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:27:13,057 [Thread-23:139962884273920] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:27:14,383 [Thread-25:139962884273920] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:27:14,624 [Thread-27:139962884273920] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:27:14,828 [Thread-29:139962884273920] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:27:17,422 [Thread-31:139962884273920] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:27:19,781 [Thread-33:139962884273920] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:28:15,999 [Thread-36:139962884273920] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:28:18,582 [Thread-38:139962884273920] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:28:59,016 [Thread-39:139962884273920] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/pages/widgets.html
2017-05-18 17:29:01,342 [Thread-41:139962892666624] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:29:02,663 [Thread-43:139962909452032] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:29:06,731 [Thread-45:139962917844736] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:29:07,208 [Thread-47:139962917844736] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:31:29,094 [Thread-49:139962917844736] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-18 17:31:29,990 [Thread-51:139962917844736] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:31:32,390 [Thread-53:139962917844736] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:32:00,666 [Thread-55:139962996639488] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:32:03,886 [Thread-57:139962901059328] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:32:06,815 [Thread-59:139962884273920] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:32:21,948 [Thread-61:139962884273920] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:32:24,166 [Thread-63:139962884273920] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-18 17:32:29,089 [Thread-65:139962884273920] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:32:33,832 [Thread-67:139962884273920] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:32:37,401 [Thread-69:139962892666624] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:32:38,454 [Thread-71:139962909452032] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:33:38,949 [Thread-77:139962996639488] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:33:41,128 [Thread-79:139962996639488] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-18 17:33:42,061 [Thread-81:139962996639488] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:33:43,340 [Thread-83:139962996639488] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:33:45,417 [Thread-85:139962996639488] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:36:11,943 [Thread-3:140138700154624] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:36:14,609 [Thread-5:140138700154624] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:37:51,491 [Thread-7:140138700154624] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:37:59,212 [Thread-9:140138700154624] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:38:22,696 [Thread-11:140138700154624] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:38:25,790 [Thread-13:140138700154624] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:38:26,211 [Thread-15:140138700154624] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:38:35,181 [Thread-18:140138691237632] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:39:09,554 [Thread-24:140138691237632] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-18 17:39:35,683 [Thread-26:140138691237632] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:40:12,826 [Thread-28:140138691237632] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-18 17:40:23,229 [Thread-30:140138691237632] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-18 17:41:14,986 [Thread-32:140138691237632] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-18 17:41:39,868 [Thread-2:139998721320704] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/pages/widgets.html
2017-05-18 17:41:42,464 [Thread-4:139998712665856] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:41:43,793 [Thread-6:139998695880448] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:41:44,740 [Thread-8:139998351324928] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:41:45,115 [Thread-10:139998351324928] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:42:10,664 [Thread-3:140537136269056] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:42:12,614 [Thread-5:140537136269056] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:42:13,464 [Thread-7:140537136269056] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:42:14,763 [Thread-9:140537136269056] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:42:18,624 [Thread-13:140537136269056] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:42:20,164 [Thread-15:140537136269056] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:42:23,987 [Thread-19:140537136269056] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:42:48,143 [Thread-3:139659763078912] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:42:50,792 [Thread-7:139659763078912] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-18 17:47:26,001 [Thread-3:139998609737472] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 17:47:51,321 [Thread-7:139998609737472] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-18 17:50:50,890 [Thread-3:139641466386176] [django.request:256] [ERROR]- Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 254, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 222, in inner
    if not self.has_permission(request):
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 162, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 226, in inner
    self._setup()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 359, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 22, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 10, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 167, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 181, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/db.py", line 21, in load
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: django_session
2017-05-18 17:51:22,165 [Thread-8:139641432815360] [django.request:256] [ERROR]- Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 254, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 222, in inner
    if not self.has_permission(request):
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 162, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 226, in inner
    self._setup()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 359, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 22, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 10, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 167, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 181, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/db.py", line 21, in load
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: django_session
2017-05-18 17:58:51,878 [Thread-14:139641542092544] [django.request:170] [WARNING]- Not Found: /
2017-05-18 17:58:58,267 [Thread-15:139641466386176] [django.request:256] [ERROR]- Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 254, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 222, in inner
    if not self.has_permission(request):
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 162, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 226, in inner
    self._setup()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 359, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 22, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 10, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 167, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 181, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/db.py", line 21, in load
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: django_session
2017-05-18 18:06:51,348 [Thread-2:139853597505280] [django.request:256] [ERROR]- Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 254, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 222, in inner
    if not self.has_permission(request):
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 162, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 226, in inner
    self._setup()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 359, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 22, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 10, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 167, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 181, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/db.py", line 21, in load
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: django_session
2017-05-18 18:06:54,233 [Thread-3:139853589112576] [django.request:256] [ERROR]- Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 254, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 222, in inner
    if not self.has_permission(request):
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 162, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 226, in inner
    self._setup()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 359, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 22, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 10, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 167, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 181, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/db.py", line 21, in load
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: django_session
2017-05-18 18:06:55,090 [Thread-4:139853580719872] [django.request:256] [ERROR]- Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 254, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 222, in inner
    if not self.has_permission(request):
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 162, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 226, in inner
    self._setup()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 359, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 22, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 10, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 167, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 181, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/db.py", line 21, in load
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: django_session
2017-05-18 18:06:55,521 [Thread-5:139853572327168] [django.request:256] [ERROR]- Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 254, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 222, in inner
    if not self.has_permission(request):
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 162, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 226, in inner
    self._setup()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 359, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 22, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 10, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 167, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 181, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/db.py", line 21, in load
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: django_session
2017-05-18 18:06:56,136 [Thread-6:139853589112576] [django.request:256] [ERROR]- Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 254, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 222, in inner
    if not self.has_permission(request):
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 162, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 226, in inner
    self._setup()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 359, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 22, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 10, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 167, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 181, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/db.py", line 21, in load
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: django_session
2017-05-18 18:07:12,829 [Thread-2:139733936133888] [django.request:256] [ERROR]- Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 254, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 222, in inner
    if not self.has_permission(request):
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 162, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 226, in inner
    self._setup()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 359, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 22, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 10, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 167, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 181, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/db.py", line 21, in load
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: django_session
2017-05-18 18:12:06,719 [Thread-3:139733936133888] [django.request:256] [ERROR]- Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 254, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 222, in inner
    if not self.has_permission(request):
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 162, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 226, in inner
    self._setup()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 359, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 22, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 10, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 167, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 181, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/db.py", line 21, in load
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: django_session
2017-05-18 18:17:36,448 [Thread-56:139733908596480] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-18 18:17:37,850 [Thread-64:139733900203776] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-18 18:18:27,794 [Thread-68:139733900203776] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-18 18:20:53,426 [Thread-2:140669787727616] [django.request:256] [ERROR]- Internal Server Error: /crawlermanage/tasks/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kui/work/python/project/geowind_crawler/crawlermanage/views.py", line 46, in tasks
    logger.info(tasks([0].get('taskname')))
AttributeError: 'list' object has no attribute 'get'
2017-05-18 18:22:51,443 [Thread-23:140669691614976] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-18 18:22:53,162 [Thread-24:140669683222272] [django.request:256] [ERROR]- Internal Server Error: /crawlermanage/tasks/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kui/work/python/project/geowind_crawler/crawlermanage/views.py", line 46, in tasks
    logger.info(tasks([0].get('taskname')))
AttributeError: 'list' object has no attribute 'get'
2017-05-18 18:30:02,160 [Thread-3:140134756488960] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-18 18:30:26,757 [Thread-9:140134739703552] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-19 01:07:03,014 [Thread-6:140109365614336] [django.request:170] [WARNING]- Not Found: /favicon.ico
2017-05-19 01:07:05,754 [Thread-14:140109365614336] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-19 01:07:08,733 [Thread-22:140109013841664] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-19 01:07:43,477 [Thread-24:140109013841664] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:07:46,146 [Thread-28:140109374007040] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-19 01:07:51,914 [Thread-30:140109374007040] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-19 01:07:54,306 [Thread-32:140109374007040] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-19 01:07:56,016 [Thread-34:140109374007040] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:08:00,448 [Thread-36:140109374007040] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-19 01:08:06,671 [Thread-38:140109374007040] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:08:10,971 [Thread-40:140109374007040] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-19 01:08:13,073 [Thread-42:140109374007040] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:08:14,105 [Thread-44:140109374007040] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-19 01:08:22,317 [Thread-46:140109374007040] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:08:24,320 [Thread-48:140109374007040] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-19 01:09:17,783 [Thread-49:140109374007040] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/pages/widgets.html
2017-05-19 01:09:20,076 [Thread-51:140109013841664] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-19 01:09:46,428 [Thread-57:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-19 01:11:49,057 [Thread-65:140109013841664] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:11:54,108 [Thread-67:140109013841664] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-19 01:11:55,716 [Thread-68:140109013841664] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/pages/widgets.html
2017-05-19 01:11:57,818 [Thread-70:140109382399744] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-19 01:12:01,308 [Thread-72:140109374007040] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-19 01:12:06,152 [Thread-74:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:12:09,441 [Thread-76:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-19 01:12:12,764 [Thread-78:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:12:16,559 [Thread-80:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:12:19,786 [Thread-82:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-19 01:12:34,821 [Thread-84:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:12:36,566 [Thread-86:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-19 01:17:38,870 [Thread-88:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-19 01:17:54,473 [Thread-90:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-19 01:17:55,525 [Thread-92:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:17:56,292 [Thread-94:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-19 01:17:58,232 [Thread-96:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:17:59,436 [Thread-98:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-19 01:18:02,331 [Thread-100:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:19:36,217 [Thread-102:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-19 01:19:36,779 [Thread-104:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:19:37,462 [Thread-106:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-19 01:19:49,021 [Thread-108:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:19:49,653 [Thread-110:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-19 01:19:50,213 [Thread-112:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:20:04,163 [Thread-114:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:20:05,178 [Thread-116:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:20:05,795 [Thread-118:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:20:06,554 [Thread-120:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:20:07,169 [Thread-122:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:20:07,696 [Thread-124:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:20:08,195 [Thread-126:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:20:09,865 [Thread-128:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:20:10,361 [Thread-130:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:20:11,090 [Thread-132:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:20:18,365 [Thread-134:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-19 01:20:19,193 [Thread-136:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:26:04,392 [Thread-138:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:27:26,338 [Thread-140:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-19 01:27:29,226 [Thread-142:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-19 01:27:30,703 [Thread-144:140109005448960] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/dist/img/user2-160x160.jpg
2017-05-19 01:35:22,542 [Thread-2:139875356047104] [django.request:170] [WARNING]- Not Found: /crawlermanage/taskdata/
2017-05-19 01:35:28,444 [Thread-6:139875256882944] [django.request:256] [ERROR]- Internal Server Error: /crawlermanage/index/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kui/work/python/project/geowind_crawler/crawlermanage/views.py", line 41, in index
    return render_to_response(request, 'crawlermanage/index.html')
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: <WSGIRequest: GET '/crawlermanage/index/'>
2017-05-19 01:35:58,099 [Thread-6:139790766823168] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-19 01:36:14,988 [Thread-3:140506327144192] [django.request:170] [WARNING]- Not Found: /crawlermanage/index/dist/img/user2-160x160.jpg
2017-05-19 01:37:15,832 [Thread-9:140505954379520] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-19 01:37:16,720 [Thread-11:140505954379520] [django.request:170] [WARNING]- Not Found: /crawlermanage/newsdata/dist/img/user2-160x160.jpg
2017-05-19 01:37:18,388 [Thread-13:140505954379520] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-19 01:37:19,299 [Thread-14:140505954379520] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/pages/widgets.html
2017-05-19 01:37:22,983 [Thread-16:140505962772224] [django.request:170] [WARNING]- Not Found: /crawlermanage/layout/dist/img/user2-160x160.jpg
2017-05-19 01:38:41,487 [Thread-21:140506335274752] [django.request:170] [WARNING]- Not Found: /crawlermanage/tasks/dist/img/user2-160x160.jpg
2017-05-19 01:38:42,788 [Thread-23:140506335274752] [django.request:170] [WARNING]- Not Found: /crawlermanage/newsdata/dist/img/user2-160x160.jpg
2017-05-19 01:38:44,861 [Thread-25:140506335274752] [django.request:170] [WARNING]- Not Found: /crawlermanage/newsdata/dist/img/user2-160x160.jpg
2017-05-19 01:38:46,038 [Thread-27:140506335274752] [django.request:170] [WARNING]- Not Found: /crawlermanage/newsdata/dist/img/user2-160x160.jpg
